<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Skills Improved</name>
   <tag></tag>
   <elementGuidId>0103f489-9808-40ae-be76-44ea1dc0b70e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Skills_Improved</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='Skills_Improved']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Skills_Improved</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d0517bab-962c-4a1e-b7c8-808fd97a3dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Skills_Improved</value>
      <webElementGuid>51ef8de4-5a40-476c-bced-1add8f17cfae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Skills Improved:</value>
      <webElementGuid>f5a47a3e-4e81-40c9-9f2a-a6cdb613db7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Skills_Improved&quot;)</value>
      <webElementGuid>7ac41098-da71-4d05-bdde-a0716e17ef0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='Skills_Improved']</value>
      <webElementGuid>c2334302-dd54-4f5a-899d-0fcbb406c6a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-579']/div/div/div/div/div/div/div/div/h2/span</value>
      <webElementGuid>73f68291-e25c-4444-8734-4829a1908e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I want a free DISCOVERY SESSION'])[2]/following::span[1]</value>
      <webElementGuid>5520bbe1-9ef0-46a9-af1b-a7913f3f1785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Java SDET Academy'])[2]/following::span[1]</value>
      <webElementGuid>6b41a196-7846-4aeb-9bc8-39a93ae6b905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How to deal with a large page that has many elements and divisions?'])[1]/preceding::span[1]</value>
      <webElementGuid>6b79a3d3-8277-4764-b40c-168b370f7775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Properly structuring your page objects'])[1]/preceding::span[1]</value>
      <webElementGuid>b5668ae9-3688-401b-809a-0fbc1b7a9ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Skills Improved:']/parent::*</value>
      <webElementGuid>b99b5324-d83c-4763-b436-a0efa7f9515c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/span</value>
      <webElementGuid>b5c573b5-e4f5-4ab9-84ea-695bad57e2d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'Skills_Improved' and (text() = 'Skills Improved:' or . = 'Skills Improved:')]</value>
      <webElementGuid>34489f41-0a75-4af0-a834-1ab7812a76dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
